### PR TITLE
Remove flows when switching type

### LINKED ISSUE #1007: Remove attached flows when switching type
# Bug report issue
## Description
Flows remain attached to previous element after switching an element to a different type.
## Reproduction steps
- Attach Sequence Flows to a Task
- Switch the Task to another type
- Download the xml and see that the flows remain
## Expected behaviour
When the previous element is replaced, the flows are removed.
## Actual behaviour
Flows remain attached to the deleted/replaced element.

### PR DESCRIPTION
**Pull request by lisa-fehr**
Closes #1007

### CODE REVIEW

File: src/components/crown/utils.js [hunk 1]
```diff
@@ -0,0 +1,10 @@
+export function removeFlows(graph, shape) {
+  graph.getConnectedLinks(this.shape).forEach(shape => this.$emit('remove-node', shape.component.node));
+  shape.getEmbeddedCells({ deep: true }).forEach(cell => {
+    if (cell.component) {
+      graph.getConnectedLinks(cell).forEach(shape => this.$emit('remove-node', shape.component.node));
+      shape.unembed(cell);
+      this.$emit('remove-node', cell.component.node);
+    }
+  });
+}
```
Comment (JCook21) [inline src/components/crown/utils.js]: I think this could probably be rewritten as a single pipeline, which would remove some of the nesting and make this more readable IMO. Something like this:
`shape.getEmbeddedCells({ deep: true })
    .filter(cell => cell.component)
    .flatMap(cell => graph.getConnectedLinks(cell))
    .foreach(shape => {
        this.$emit('remove-node', shape.component.node));
        shape.unembed(cell);
        this.$emit('remove-node', cell.component.node);
    });
`

File: src/components/crown/utils.js [hunk 2]
```diff
@@ -0,0 +1,10 @@
+export function removeFlows(graph, shape) {
+  graph.getConnectedLinks(this.shape).forEach(shape => this.$emit('remove-node', shape.component.node));
+  shape.getEmbeddedCells({ deep: true }).forEach(cell => {
+    if (cell.component) {
+      graph.getConnectedLinks(cell).forEach(shape => this.$emit('remove-node', shape.component.node));
+      shape.unembed(cell);
+      this.$emit('remove-node', cell.component.node);
+    }
+  });
```
Comment (JCook21) [inline src/components/crown/utils.js]: `I think this could probably be rewritten as a single pipeline, which would remove some of the nesting and make this more readable IMO. Something like this:
`shape.getEmbeddedCells({ deep: true })
    .filter(cell => cell.component)
    .flatMap(cell => graph.getConnectedLinks(cell))
    .foreach(shape => {
        this.$emit('remove-node', shape.component.node));
        shape.unembed(cell);
        this.$emit('remove-node', cell.component.node);
    });
`

Comment (JCook21) [reply src/components/crown/utils.js]: I just realized that this is just a refactoring in moving this code to this place. I still think it's a good time to make an improvement though. :)
