### PR TITLE
Fix lane overlap bug

### LINKED ISSUE #824: Pool Lanes can hide content
Create/edit a process, add multiple controls

Add a pool control

Add at least one extra pool lane

Change the height of one of the pool lanes

Result:

Controls get hidden by the movement of additional pool lanes, can no longer be selected while hidden.

https://www.dropbox.com/s/i88kj81t1npf26q/pools-lanes-overlapping.mp4?dl=0

### PR DESCRIPTION
**Pull request by chipit24**
Fixes #824.

### CODE REVIEW

**Comment by chipit24** [comment]
The single failing test in this branch is the one I added, "_should not cover child elements with lane_", which is expected.

File: src/components/Modeler.vue [hunk 1]
```diff
@@ -160,6 +158,7 @@ import registerInspectorExtension from '@/components/InspectorExtensionManager';
 
 import initAnchor from '@/mixins/linkManager.js';
 import { addIdToNodeAndSetUpDiagramReference, addNodeToProcess, getTargetProcess } from '@/components/nodeManager';
+import ensureShapeIsNotCovered from '@/components/shapeStackUtils';
```
Comment (chipit24) [inline src/components/Modeler.vue]: This name could be improved, but I figured it's better than `setShapeStacking`, and avoids describing what's happening in an imperative way: it should be clear that we're not concerned about setting specific z-indices, but about making sure a shape isn't covered or overlapping another shape.

File: src/components/nodes/poolLane/index.js [hunk 2]
```diff
@@ -3,8 +3,6 @@ import idConfigSettings from '@/components/inspectors/idConfigSettings';
 import nameConfigSettings from '@/components/inspectors/nameConfigSettings';
 
 export const id = 'processmaker-modeler-lane';
-export const minLaneHeight = 100;
-
```
Comment (chipit24) [inline src/components/nodes/poolLane/index.js]: This export wasn't actually used anywhere, and the value for the minimum lane height is specified in `src/components/nodes/poolLane/laneSizes.js`.

File: tests/e2e/specs/Pools.spec.js [hunk 3]
```diff
@@ -228,4 +230,29 @@ describe('Pools', () => {
...
+      .then($pool => {
+        getCrownButtonForElement($pool, 'lane-above-button').click({ force: true });
+      });
+
+    const startEventPosition = { x: 150, y: 150 };
+    const topLanePosition = { x: startEventPosition.x, y: startEventPosition.y - 50 };
+    getPositionInPaperCoords(startEventPosition).then(({ x, y }) => {
+      getElementAtPosition(topLanePosition, nodeTypes.poolLane).click();
+
+      cy.get('.main-paper [button-id="bottom-right-resize-button"]')
```
Comment (lisa-fehr) [inline tests/e2e/specs/Pools.spec.js]: Nice. I do see that there can be two bottom-right-resize-buttons. But it seems to work regardless.
Screen Shot 2019-11-21 at 2 33 31 PM

File: src/components/shapeStackUtils.js [hunk 4]
```diff
@@ -0,0 +1,54 @@
...
+}
+
+function getElementPool(shape) {
+  return shape.component.node.pool;
+}
+
+function isPool(shape) {
+  return shape.component.node.type === poolId;
+}
+
```
Comment (chipit24) [inline src/components/shapeStackUtils.js]: I thought about adding unit tests for this, but I wasn't sure it would add any value. The heavy-lifting is accomplished by calls to `toFront`, and tests would essentially be verifying that `toFront` was called in the correct order, the correct number of times.

There might be better combinations of calling `toFront` that also fix overlapping issues, or maybe there's a different JointJS function we could use. I think unit tests could slow us down in those cases, and I think this functionality is sufficiently covered by our e2e tests. 

Maybe that's a hint that this isn't the best (or correct abstraction) right now, but I think it's still much better than having all this logic spread into `Modeler.vue`.

File: src/mixins/resizeConfig.js [hunk 5]
```diff
@@ -464,12 +459,20 @@ export default {
...
-        button.attr('root/display', 'initial');
+        try {
+          this.shape.embed(button);
+        } catch (error) {
+          /* There is an error when re-adding points after removing/re-adding the pool.
+           * Ignore it for now. */
+        }
+
+        button.addTo(this.graph);
+        button.toFront();
```
Comment (chipit24) [inline src/mixins/resizeConfig.js]: The left corner handles were hidden behind the pool, so I had to call this to ensure it was always visible.

File: tests/e2e/specs/Pools.spec.js (hunk 3 above)
Comment (chipit24) [reply tests/e2e/specs/Pools.spec.js]: How did you search for the 2nd bottom right resize button? It seems to not be visible in the screenshot above. I think it may be part of the mini-map paper, which I think duplicates the handles as well.

Comment (lisa-fehr) [reply tests/e2e/specs/Pools.spec.js]: I highlighted the pool and then did a text search in the Elements console. The other bottom right resize was where I expected it to be.

You are correct. It is the mini-map!
