### PR TITLE
Fix startEvent props update after undo

### LINKED ISSUE #251: Unable to change start event properties after undo
**Steps to reproduce:**
1. Select the start event, and change both it's ID and its name.
2. Press `Undo`, and repeat step 1 above.
3. After undo, updates to the node inspector aren't persisted to the element.

**Expected behaviour:**
* You should be able to update all node properties before and after undo/redo.

**Gif of problem:**
undo_bug

### PR DESCRIPTION
**Pull request by chipit24**
Fixes #251.

**How to test:**
* Visit the issue linked above and ensure you cannot reproduce the bug, and that you experience the expected behaviour.

### CODE REVIEW

File: src/components/inspectors/InspectorPanel.vue [hunk 1]
```diff
@@ -106,7 +106,7 @@ export default {
     }, saveDebounce),
     defaultInspectorHandler(value, node, setNodeProp) {
       /* Go through each property and rebind it to our data */
-      for (const key in value) {
+      for (const key in omit(value, ['$type', 'eventDefinitions'])) {
```
Comment (caleeli) [inline src/components/inspectors/InspectorPanel.vue]: I think that Array properties (like eventDefinitions) represents child nodes and not attributes, may be this could be improved
