### PR TITLE
Fix sequence flow alignment

### LINKED ISSUE #690: Round elements seem to be horizontally off centre
Round elements seem to be horizontally off centre, causing the initial flow element to be not straight

### PR DESCRIPTION
**Pull request by chipit24**
Fixes #690.

### CODE REVIEW

File: src/components/nodes/task/index.js [hunk 1]
```diff
@@ -1,8 +1,8 @@
 import component from './task.vue';
 import idConfigSettings from '@/components/inspectors/idConfigSettings';
 import nameConfigSettings from '@/components/inspectors/nameConfigSettings';
+import { taskHeight, taskWidth } from './taskConfig';
 
-export const taskHeight = 76;
```
Comment (JCook21) [inline src/components/nodes/task/index.js]: What's the advantage of moving these constants to a separate file?

File: src/components/nodes/startEvent/startEventConfig.js [hunk 2]
```diff
@@ -0,0 +1 @@
+export const startEventDiameter = 36;
```
Comment (JCook21) [inline src/components/nodes/startEvent/startEventConfig.js]: What's the advantage of having this single constant in a file?

File: src/components/Modeler.vue [hunk 3]
```diff
@@ -687,12 +687,9 @@ export default {
...
 
-      // Handle transform
-      const paperOrigin = this.paperManager.localToPagePoint(0, 0);
-      const scale = this.paperManager.scale;
-
-      diagram.bounds.x = (clientX - paperOrigin.x) / scale.sx;
-      diagram.bounds.y = (clientY - paperOrigin.y) / scale.sy;
+      const { x, y } = this.paperManager.clientToGridPoint(clientX, clientY);
+      diagram.bounds.x = x;
+      diagram.bounds.y = y;
```
Comment (JCook21) [inline src/components/Modeler.vue]: Nice extraction!

File: tests/unit/paperManager.spec.js [hunk 4]
```diff
@@ -0,0 +1,31 @@
...
+    'Can convert client position to grid position',
+    (scale, paperOrigin, clientX, clientY, expectedPoint) => {
+      paper.scale = () => scale;
+      paper.localToPagePoint = () => paperOrigin;
+
+      const actualPoint = paperManager.clientToGridPoint(clientX, clientY);
+      expect(actualPoint).toEqual(expectedPoint);
+    });
+});
+
```
Comment (JCook21) [inline tests/unit/paperManager.spec.js]: Awesome! 🔥

File: tests/unit/paperManager.spec.js [hunk 5]
```diff
@@ -0,0 +1,31 @@
...
+  let paperManager;
+  let paper;
+
+  beforeEach(() => {
+    paper = {};
+    paperManager = new PaperManager(paper);
+  });
+
+  test.each(positionData)(
```
Comment (JCook21) [inline tests/unit/paperManager.spec.js]: Do you prefer `test` or `it` for these? They're equivalent so it's a matter of preference. I think we should keep it consistent though.

File: src/components/nodes/task/index.js (hunk 1 above)
Comment (JCook21) [reply src/components/nodes/task/index.js]: I've just seen them used in tests, which makes sense. I still wonder about not extracting them to separate files though.

File: src/components/nodes/startEvent/startEventConfig.js (hunk 2 above)
Comment (JCook21) [reply src/components/nodes/startEvent/startEventConfig.js]: I've just seen them used in tests, which makes sense. I still wonder about not extracting them to separate files though.

**Comment by JCook21** [comment]
I think this seems good to go. What's remaining to be done to take this out of WIP?

File: tests/unit/paperManager.spec.js (hunk 5 above)
Comment (chipit24) [reply tests/unit/paperManager.spec.js]: Oh, wasn't paying attention to that! I'll change it to use `it` for consistency.

File: src/components/nodes/startEvent/startEventConfig.js (hunk 2 above)
Comment (chipit24) [reply src/components/nodes/startEvent/startEventConfig.js]: With this, and the task height/width, if I keep them in the same `index.js` file, Cypress complains that it can't parse the file due to the imports:

```bash
SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'
    at EventEmitter.handler (/Users/robertkomaromi/Library/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:67:29)
    at emitOne (events.js:116:13)
    at EventEmitter.emit (events.js:211:7)
    at ChildProcess.<anonymous> (/Users/robertkomaromi/Library/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:25:29)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

Our babel setup should handle the ES module synatax, so it appears that Cypress doesn't run the test files through babel, or there's some configuration mismatch. I bug into it a little but didn't get far so decided this was the easier option.

I can look into it more, as it would be nicer so keep them in the same file.

Comment (JCook21) [reply src/components/nodes/startEvent/startEventConfig.js]: Interesting. Let's not hold this up for now but we can fix that later if you like.

Comment (chipit24) [reply src/components/nodes/startEvent/startEventConfig.js]: Sounds good; I can fix it later and not let this hold it up right now.
