### PR TITLE
Fix z-index with sequence flows

### LINKED ISSUE #231: Sequence flow layering issue with pools
**Steps to reproduce**
1. Drag any element
2. Connect Start Event to element to create a `sequence flow`
3. Drag a pool
 
sequence-flow

### PR DESCRIPTION
**Pull request by tuantruong625**
**Bug**
When dragging a pool onto the paper, the sequences flows are hidden behind the pool.

1. Drag any element
2. Connect Start Event to element to create a `sequence flow`
3. Drag a pool

sequence-flow

**Fix**

sequence-flow-fix

Fixes #231

### CODE REVIEW

File: src/mixins/crownConfig.js [hunk 1]
```diff
@@ -107,6 +107,7 @@ export default {
       }
 
       this.$emit('add-node', {
+        id: 'sequence-flow-button',
```
Comment (chipit24) [inline src/mixins/crownConfig.js]: This can be removed; `addNode` doesn't do anything with `id`, and the "add sequence flow" buttons for task, start event and gateway already have IDs set.
