### PR TITLE
Fix issues with error highlighting after resizing

### LINKED ISSUE #470: Validation border render issue with lanes
**Issue**

When there is an error with lanes and the user attempts to resize pool/lane the red error borders will not update with the pool/lane and becomes fixed to the last size of the pool/lane.

**How to reproduce**
- Create a pool with a lane that has an error (missing label error)
- Resize the pool/lane

**Expected**
- Red error border adjust to the resize of the pool/lane

**Screenshot**
Screen Shot 2019-07-08 at 4 32 23 PM

**Video of bug**
https://drive.google.com/open?id=1esMRws8fJjKIEb8KG8dNLhJxAUx94Yki

### PR DESCRIPTION
**Pull request by JCook21**
Closes #470.

Resolves an issue where error highlights were not changing after an element is resized. After this I decided to refactor the code to simplify things.

### CODE REVIEW

File: src/mixins/highlightConfig.js [hunk 1]
```diff
@@ -56,53 +56,28 @@ export default {
...
-    setHighlight() {
-      if (this.highlighted) {
-        this.shapeView.highlight(this.shapeBody, { highlighter: defaultHighlighter });
-        return;
-      }
-
-      this.shapeView.unhighlight(this.shapeBody, { highlighter: defaultHighlighter });
-    },
-    setErrorHighlight() {
+    setShapeHighlight() {
```
Comment (JCook21) [inline src/mixins/highlightConfig.js]: I decided to merge the highlighting code into a single method for simplicity.

File: src/mixins/highlightConfig.js [hunk 2]
```diff
@@ -56,53 +56,28 @@ export default {
...
-      this.shape.on('change:size', () => {
-        if (this.paperManager.hasScheduledUpdates()) {
-          this.paperManager.addOnceHandler('render:done', this.reHighlightExpandedElement);
-          return;
-        }
-        this.reHighlightExpandedElement();
-      });
-    },
-    reHighlightExpandedElement() {
+      this.shapeView.unhighlight(this.shapeBody, defaultHighlighter);
```
Comment (JCook21) [inline src/mixins/highlightConfig.js]: Unhighlighting and then rehighlighting doesn't seem to cause any issues with flicker, etc. It seemed to be simpler and more consistent to bring this all into a single method.

File: src/components/paperManager.js [hunk 3]
```diff
@@ -94,7 +94,11 @@ export default class PaperManager {
     this.paper.drawBackground({ color: defaultNodeColor });
   }
 
-  hasScheduledUpdates() {
-    return this.#paper._updates.priorities.some(updates => !util.isEmpty(updates));
+  executeAfterScheduledUpdates(callback) {
```
Comment (JCook21) [inline src/components/paperManager.js]: This gets rid of some duplication and better encapsulates the logic of how this callback is handled.
