### PR TITLE
Boundary Event Bug

### LINKED ISSUE #1069: Boundary timer event disappearing on redo
# Bug report issue
## Description
The boundary timer event unexpectedly disappears after undo/redo.

## Reproduction steps
1. Drag a regular Task onto the paper.
2. Open the Boundary Events dropdown from the crown config and add a Boundary Timer Event to the task.
3. Open the Advanced accordion and modify the Node Identifier (e.g. add a letter), then press Undo, then press Redo.
4. Repeat step 3 above.

## Expected behaviour
The boundary event should remain visible, and no console error should be thrown.

## Actual behaviour
After step 4 (the 2nd redo), the boundary event disappears and the following error is thrown in the console:
```
[Vue warn]: Error in mounted hook (Promise/async): "TypeError: Cannot read property 'bounds' of undefined"

found in
---> <ProcessmakerModelerBoundaryTimerEvent> at src/components/nodes/boundaryTimerEvent/boundaryTimerEvent.vue
```

## Software used
Latest modeler `develop` branch running on Google Chrome 79 on macOS Catalina.

## Other information
Video of issue: https://www.dropbox.com/s/5xm3um7qcqlquch/boundary_timer_event_redo_bug.mov?dl=0.

### PR DESCRIPTION
**Pull request by tuantruong625**
Fixes #1069.

### CODE REVIEW

File: src/components/modeler/Modeler.vue [hunk 1]
```diff
@@ -580,17 +580,21 @@ export default {
...
       });
     },
+    replaceDefinition(definition, boundaryEvent, process) {
+      const definitionIndex = process.get('flowElements').indexOf(definition);
+      process.flowElements[definitionIndex] = boundaryEvent;
+      const boundaryEventDiagram = this.planeElements.find((diagram) => {
+        return diagram.bpmnElement === definition;
+      });
+      boundaryEventDiagram.bpmnElement = boundaryEvent;
+    },
```
Comment (chipit24) [inline src/components/modeler/Modeler.vue]: Every shape in the BPMN diagram has a "shape" object (`BPMNShape`, `BPMNEdge`, etc.) in bpmn-moddle that references the definition object. The issue was that when the boundary event definition was replaced, the diagram element still referenced the unused definition object from before.

This fix grabs the diagram object and updates its definition reference.
