### PR TITLE
Sub Process name fixes

### LINKED ISSUE #1142: Sub Process Name is Difficult
This might already be fixed, but the naming in the inspector of a sub process is uncooperative. You can't type in the field.

### LINKED ISSUE #1143: Do not replace sub process name with selected process
If you type/paste in a name for a subprocess, it should not get overwritten if you select a process.
Saved subprocess names should not be overwritten after selecting a process as well.

Related #1142

### PR DESCRIPTION
**Pull request by lisa-fehr**
Do not allow the sub process name to be set as undefined
Closes #1142 

Do not change sub process name when selecting a process
Closes #1143 

Changes the behavior of this pr: https://github.com/ProcessMaker/modeler/pull/1052

### CODE REVIEW

File: src/components/nodes/subProcess/index.js [hunk 1]
```diff
@@ -39,8 +39,8 @@ export default {
 
     setNodeProp(node, 'calledElement', currentConfig.calledElement);
 
-    if (currentConfig.name != value.name) {
-      if (oldConfig.name === value.name || !oldConfig.name) {
+    if (currentConfig.name !== value.name) {
+      if (currentConfig.name && (oldConfig.name === value.name || !oldConfig.name)) {
```
Comment (chipit24) [inline src/components/nodes/subProcess/index.js]: I find this block a little hard to read. I wonder if it can be pulled out into a function and then refactored.

Comment (lisa-fehr) [reply src/components/nodes/subProcess/index.js]: I wasn't 100% sure what it is doing to give it a name.

Comment (johnblackspear) [reply src/components/nodes/subProcess/index.js]: Random name suggestions, feel free to ignore:

`currentConfig.name !== value.name` ==> `nameChanged`

`currentConfig.name && (oldConfig.name === value.name || !oldConfig.name)` ==> `nameChangedByFormSelect`

Or something like that, not sure my suggestion is an improvement :)

File: src/components/nodes/subProcess/index.js [hunk 2]
```diff
@@ -34,14 +39,12 @@ export default {
...
 
-    const oldConfig = JSON.parse(node.definition.config);
     const currentConfig = JSON.parse(value.config);
 
     setNodeProp(node, 'calledElement', currentConfig.calledElement);
 
     if (currentConfig.name !== value.name) {
-      if (currentConfig.name && (oldConfig.name === value.name || !oldConfig.name)) {
-        // SubProcessFormSelect automatically updated the name so set the new name here
+      if (subProcessFormSelected(value.name, node) && currentConfig.name) {
```
Comment (chipit24) [inline src/components/nodes/subProcess/index.js]: I don't know if this helps with readability for me. I like what @johnblackspear suggested, taking this whole line and moving it into a function with a name like "nameChangedByFormSelect". The current name, for me, suggests that some form in a sub process was selected.
