### PR TITLE
Fix console error when adding lane

### LINKED ISSUE #908: Error when adding lane to pool containing boundary event
##  Description
A console error is thrown when adding a lane to a pool which contains a boundary event.

## Reproduction steps
* Drag a generic task onto the grid.
* Drag a boundary event onto the task.
* Drag a pool onto the grid.
* Add a lane to the pool.

Note: The order above is important. The error doesn't occur when the pool is added fist.

## Expected behaviour
No console errors are thrown.

## Actual behaviour
The following console error is thrown:
```
[Vue warn]: Error in nextTick: "TypeError: Cannot read property 'component' of null"
```

## Software used
Standalone modeler develop branch, Chrome 78, macOS Catalina.

### PR DESCRIPTION
**Pull request by chipit24**
Fixes #908.

### CODE REVIEW

File: src/components/nodes/pool/pool.vue [hunk 1]
```diff
@@ -250,6 +251,7 @@ export default {
 
         this.getElementsUnderArea(element, this.graph).filter(laneElement => {
           return laneElement.component &&
```
Comment (JCook21) [inline src/components/nodes/pool/pool.vue]: This expression is getting quite long and complicated. Could it be split into multiple calls to `filter()`? Another option would be to move it to a method and give it a descriptive name.

Comment (chipit24) [reply src/components/nodes/pool/pool.vue]: I was going to move this whole block into another function as it's using an early return but it's hard to tell. I agree that this is a huge function that needs to be broken up though.

Comment (JCook21) [reply src/components/nodes/pool/pool.vue]: Multiple calls to `.filter()` would make this more readable IMO.
